server:
  port: 8761
eureka:
  enableSelfPreservation: false
  leaseRenewalIntervalInSeconds: 2
  instance:
    hostname: peer1 
  
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/